//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvien
    {
        public int nhanvienid { get; set; }
        public int idphongban { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public int nhomqtid { get; set; }
        public System.DateTime datecreate { get; set; }
        public Nullable<System.DateTime> datedelete { get; set; }
        public int quoctichid { get; set; }
        public string usename { get; set; }
    }
}
