//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomQT
    {
        public int idnhomqt { get; set; }
        public string tennhomqt { get; set; }
        public System.DateTime datecreate { get; set; }
        public System.DateTime datedelete { get; set; }
        public bool isdelete { get; set; }
        public bool isblocked { get; set; }
    }
}
