//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phongban
    {
        public int phongbanID { get; set; }
        public string namephongban { get; set; }
        public int idparent { get; set; }
        public string diachipb { get; set; }
        public string sdt { get; set; }
        public System.DateTime datecreate { get; set; }
        public System.DateTime datedelete { get; set; }
        public int idnhanvien { get; set; }
        public int nhomqtid { get; set; }
    }
}
